services:
  video-upload-service:
    build:
      context: .
      dockerfile: dockerfiles/video-upload-service/Dockerfile
    ports:
      - "3000:80"
  gateway-service:
    build:
      context: .
      dockerfile: dockerfiles/gateway-service/Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    command: ["uvicorn", "src.Presentation.Routes.main:app", "--host", "0.0.0.0", "--port", "80"]
  relay-service:
    build:
      context: .
      dockerfile: dockerfiles/relay-service/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
  minio:
    image: minio/minio:RELEASE.2025-01-18T00-31-37Z
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      MINIO_ACCESS_KEY: hao
      MINIO_SECRET_KEY: nghiemxuan
    command: server /data --console-address ":9001"
    # volumes:
      # - ./minio/data:/data
      # - ./minio/config:/root/.minio
