sequenceDiagram
    participant Client as Client (Browser)
    participant A as Peer A (Requester Peer - Gateway)
    participant Cache as Local Cache
    participant TURN as Relay Server
    participant B as Peer B (Provider Peer)
    
    A->>TURN: emit(register peer)
    TURN-->>A: listen event 'response' from relay server
    
    B->>TURN: emit(register peer)
    TURN-->>B: listen event 'request' from relay server
    
    Client->>A: HTTP Request

    A->>Cache: Check if CID in cache
    Cache->>A: Don't have cached CID

    A->>TURN: emit(HTTP request)
    TURN->>B: Forward HTTP Request
    
    B->>TURN: emit(HTTP Response)
    TURN->>A: Forward HTTP Response
    A->>Client: HTTP Response
